---
apiVersion: v1
data:
  rabbitmq-pass: Z1A1aWNMak5QMmd2
kind: Secret
metadata:
  labels:
    app: rabbitmq-exporter
  name: rabbitmq-rabbitmq-secret
  namespace: default
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq-exporter
  name: rabbitmq-exporter
  namespace: default
spec:
  selector:
    app: rabbitmq-exporter
  ports:
  - port: 80
    targetPort: 9090
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: rabbitmq-exporter
  namespace: default
  labels:
    app: rabbitmq-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-exporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rabbitmq-exporter
        version: "0"
    spec:
      containers:
        - name: rabbitmq-exporter
          image: kbudde/rabbitmq-exporter:v0.29.0
          imagePullPolicy: Always
          env:
            - name: RABBIT_URL
              value: "http://rabbitmq-1-rabbitmq-svc.default:15672"
            - name: RABBIT_USER
              value: rabbit
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-rabbitmq-secret
                  key: rabbitmq-pass
            - name: LINES
              value: "42"
            - name: COLUMNS
              value: "178"
          ports:
            - containerPort: 9090
          livenessProbe:
            httpGet:
              path: /
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30

